// Generated by CoffeeScript 1.3.1

/*
propagation-delay.coffee 
by Michelle Phung for DDO 2013

(coffeescript file for digital design book fulladder with transistors)

May 24th, 2012
*/


(function() {
  var black, blue, fontfamily, gray, orange, r, red, teal, white;

  black = '#000';
  white = "#fff";
  gray = '#808080';
  blue = '#df80ff';
  orange = "#FFA347";
  teal = '#18e99f';
  red = "#f00";

  fontfamily = '"HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif';

  r = null;

  $(function() {
    var bucket, bucketcounter, createMovingDots, dotTimerVariable, end, start;
    r = new Raphael("propagation-delay-widget-ralph", 1000, 1000);
    start = 100;
    end = 500;
    dotTimerVariable = null;
    r.text(50, 700, "off").attr({
      'font-family': fontfamily,
      'font-size': '50px',
      'fill': teal
    }).click(function() {
      return window.clearInterval(dotTimerVariable);
    });
    r.text(50, 650, "on").attr({
      'font-family': fontfamily,
      'font-size': '50px',
      'fill': teal
    }).click(function() {
      return dotTimerVariable = setInterval(function() {
        return createMovingDots("M100,100 h500 v150 h-300 v100 h400 v 130 h-200 v-200 h300 v250 h100 v100 h-400 v100");
      }, 300);
    });
    bucket = r.path("M475,700 h50 v50 h-50 v-50");
    bucketcounter = r.text(500, 725, 0).attr({
      'font-family': fontfamily,
      'font-size': '25px',
      'fill': teal
    });
    return createMovingDots = function(pathstring) {
      var dot, length, pathForDots;
      pathForDots = r.path(pathstring).hide();
      length = pathForDots.getTotalLength();
      console.log("hello");
      r.customAttributes.distance = function(value) {
        var point;
        value = (length / 100) * value;
        point = pathForDots.getPointAtLength(value);
        return {
          cx: point.x,
          cy: point.y
        };
      };
      return dot = r.circle().attr({
        distance: 0,
        r: 20,
        stroke: teal,
        fill: teal,
        'fill-opacity': 0.5
      }).animate({
        distance: 100
      }, 15000, "linear", function() {
        this.remove();
        return bucketcounter.attr('text', parseInt(bucketcounter.attr('text')) + 1);
      });
    };
  });

}).call(this);
