// Generated by CoffeeScript 1.3.1
(function() {
  var black, blue, fontfamily, gray, orange, purple, red, white;

  black = '#000';
  white = "#fff";
  gray = '#B3B3B3';
  orange = "#24248F";
  purple = "#8A2BE2";
  blue = '#7922A2';
  fontfamily = '"HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif';

  window.onload = function() {
    var CI_0, CI_1, CI_2, CI_3, CO_0, CO_1, CO_2, CO_3, a, a0, a0_clicked, a1, a1_clicked, a2, a2_clicked, a3, a3_clicked, b, b0, b0_clicked, b1, b1_clicked, b2, b2_clicked, b3, b3_clicked, c, carryIn_clicked, changeCarry, changeSum, ci0, ci1, ci2, ci3, clickInputs, co0, co1, co2, co3, d, e, f, g, getValue, h, inputA_0, inputA_1, inputA_2, inputA_3, inputB_0, inputB_1, inputB_2, inputB_3, labels, makeMovingLine, r, rca, showWires, showWiresHelper, subA_0, subA_1, subA_2, subA_3, subB_0, subB_1, subB_2, subB_3, subCI_0, subCI_1, subCI_2, subCI_3, subCO_0, subCO_1, subCO_2, subCO_3, sub_s0, sub_s1, sub_s2, sub_s3, subscript_size, sum0, sum1, sum2, sum3, sum_0, sum_1, sum_2, sum_3, text_size, toggle, updateOutput;
    r = new Raphael('ripple-ralph', 981, 981);
    rca = r.set().push(
    	a = r.path('M385.182,485.745v-25h-289v-101h37.55l-2.81,2.61l0.68,0.729l4.4-4.08l-4.4-4.09l-0.68,0.73l3.33,3.1\
				h-39.07v103h289v24h-134.27c-0.881-2.96-5.48-13.12-26.671-14h-6.529l0.42,0.75c0.06,0.1,5.93,10.47,5.859,13.99\
				c-0.079,3.779-5.8,14.42-5.859,14.52l-0.4,0.74h6.311c21.83-2.01,26.84-14.42,27.05-14.94l0.02-0.06h134.07v82h-18v1h19v-83h538\
				v-1H385.182z M222.972,500.745h-4.57c1.33-2.53,5.511-10.78,5.59-14.24c0.061-3.24-4.189-11.26-5.569-13.76h4.8\
				c22.13,0.92,25.55,12.45,25.88,13.83C248.512,487.896,242.991,498.896,222.972,500.745z'), 
    	b = r.path('M296.212,567.745c-0.931-2.83-5.601-12.26-26.65-14h-6.53l0.42,0.75c0.04,0.06,2.421,4.28,4.131,8.25h-8.4\
				v-11h-34.18c0-7.72-6.28-14-14-14h-18.82v7h-13v-34.24c0.63-0.29,1.07-0.939,1.07-1.689c0-0.021,0-0.051-0.011-0.07h12.94v-14\
				h23.31c-1.56,3.38-3.27,6.43-3.3,6.48l0.87,0.489c0.24-0.43,5.99-10.68,5.98-14.67c0-1.479-0.83-3.85-1.86-6.24\
				c-0.01-0.02-0.02-0.04-0.03-0.06c-1.689-3.9-3.939-7.85-4.09-8.12l-0.87,0.5c0.04,0.061,2.19,3.84,3.87,7.62h-50.689\
				c-0.2-0.81-0.931-1.41-1.811-1.41s-1.61,0.601-1.81,1.41h-6.521c-0.89-2.96-5.49-13.12-26.68-14h-6.53l0.43,0.75\
				c0.061,0.1,5.921,10.47,5.851,13.99c-0.08,3.779-5.8,14.42-5.86,14.52l-0.399,0.74h6.29c21.859-1,27.029-14.82,27.069-14.96\
				l0.021-0.04h6.35c0.18,0.66,0.73,1.17,1.41,1.31v24.69h-64v-17.26c0.9-0.09,1.61-0.83,1.66-1.74h21.46\
				c-1.67,3.79-3.76,7.52-3.8,7.58l0.88,0.49c0.24-0.431,5.99-10.69,5.979-14.67c-0.02-3.931-5.739-14-5.989-14.42l-0.86,0.489\
				c0.03,0.05,1.46,2.561,2.89,5.53H84.252c-0.33-0.49-0.9-0.81-1.54-0.81c-0.641,0-1.21,0.319-1.54,0.81h-18.99v1h18.66\
				c-0.01,0.02-0.01,0.05-0.01,0.07c0,0.85,0.569,1.569,1.35,1.79v11.14h-20v1h20v19h-20v1h20v92h110v5h18.82\
				c7.38,0,13.449-5.74,13.96-13h34.22v-15h6.89c-1.34,2.87-2.59,5.21-2.62,5.26l-0.399,0.74h6.28c21.859-1,27.029-14.82,27.08-14.96\
				l0.01-0.04h14.76v-1H296.212z M129.302,495.745h-4.59c1.33-2.53,5.52-10.78,5.59-14.24c0.07-3.24-4.19-11.26-5.57-13.76h4.8\
				c22.17,0.92,25.57,12.49,25.881,13.83C154.852,482.936,149.372,494.815,129.302,495.745z M193.182,538.745h17.82\
				c7.17,0,13,5.83,13,13s-5.83,13-13,13h-17.82V538.745z M165.182,482.976c0.57-0.181,1.01-0.65,1.17-1.23h51.14\
				c0.891,2.09,1.551,4.07,1.551,5.31c0,1.511-0.95,4.12-2.091,6.69h-24.77v14h-12.27c-0.33-0.49-0.9-0.81-1.54-0.81\
				c-0.641,0-1.21,0.319-1.54,0.81h-11.65V482.976z M165.182,508.745h11.32c-0.011,0.02-0.011,0.05-0.011,0.07\
				c0,0.97,0.74,1.77,1.69,1.859v35.07h14v12h-27V508.745z M83.182,476.625c0.81-0.2,1.41-0.93,1.41-1.81c0-0.021,0-0.051-0.01-0.07\
				h38.29c1.3,2.78,2.489,5.75,2.489,7.4c0,1.3-0.699,3.399-1.62,5.6h-22.119c-0.301-0.6-0.931-1-1.65-1s-1.35,0.4-1.65,1h-15.14\
				V476.625z M83.182,488.745h14.92c0.04,0.71,0.47,1.31,1.08,1.58v17.42h-16V488.745z M192.182,599.745h-109v-91h16v79h93V599.745z\
				 M211.002,604.745h-17.82v-26h17.82c7.17,0,13,5.83,13,13S218.172,604.745,211.002,604.745z M258.182,576.745v15h-33.18\
				c0-7.72-6.28-14-14-14h-18.82v9h-92v-78h64v50h28v7h18.82c7.38,0,13.449-5.74,13.96-13h33.22v11h9.83\
				c0.76,1.9,1.31,3.65,1.29,4.74c-0.04,1.81-1.38,5.21-2.771,8.26H258.182z M269.302,582.745h-4.58c0.52-0.99,1.479-2.87,2.46-5\
				c1.52-3.28,3.08-7.14,3.12-9.24c0.07-3.25-4.19-11.26-5.561-13.76h4.771c22.12,1.83,25.57,12.54,25.9,13.84\
				C294.842,569.965,289.352,581.815,269.302,582.745z'), 
		c = r.path('M423.212,417.745c-0.931-2.83-5.601-12.26-26.65-14h-6.53l0.42,0.75c0.04,0.06,2.421,4.28,4.131,8.25\
					h-8.4v-11h-34.18c0-7.72-6.28-14-14-14h-18.82v7h-13v-34.24c0.63-0.29,1.07-0.939,1.07-1.689c0-0.021,0-0.051-0.011-0.07h12.94\
					v-14h23.31c-1.56,3.38-3.27,6.43-3.3,6.48l0.87,0.489c0.24-0.43,5.99-10.68,5.98-14.67c0-1.479-0.83-3.85-1.86-6.24\
					c-0.01-0.02-0.02-0.04-0.03-0.06c-1.689-3.9-3.939-7.85-4.09-8.12l-0.87,0.5c0.04,0.061,2.19,3.84,3.87,7.62h-50.689\
					c-0.2-0.81-0.931-1.41-1.811-1.41s-1.61,0.601-1.81,1.41h-6.521c-0.89-2.96-5.49-13.12-26.68-14h-6.53l0.43,0.75\
					c0.061,0.1,5.921,10.47,5.851,13.99c-0.08,3.779-5.8,14.42-5.86,14.52l-0.399,0.74h6.29c21.859-1,27.029-14.82,27.069-14.96\
					l0.021-0.04h6.35c0.18,0.66,0.73,1.17,1.41,1.31v24.69h-64v-17.26c0.9-0.09,1.61-0.83,1.66-1.74h21.46\
					c-1.67,3.79-3.76,7.52-3.8,7.58l0.88,0.49c0.24-0.431,5.99-10.69,5.979-14.67c-0.02-3.931-5.739-14-5.989-14.42l-0.86,0.489\
					c0.03,0.05,1.46,2.561,2.89,5.53h-38.149c-0.33-0.49-0.9-0.81-1.54-0.81c-0.641,0-1.21,0.319-1.54,0.81H62.182v1h145.66\
					c-0.01,0.02-0.01,0.05-0.01,0.07c0,0.85,0.569,1.569,1.35,1.79v11.14h-147v1h147v19h-20v1h20v92h110v5h18.82\
					c7.38,0,13.449-5.74,13.96-13h34.22v-15h6.89c-1.34,2.87-2.59,5.21-2.62,5.26l-0.399,0.74h6.28\
					c21.859-1,27.029-14.82,27.08-14.96l0.01-0.04h14.76v-1H423.212z M256.302,345.745h-4.59c1.33-2.53,5.52-10.78,5.59-14.24\
					c0.07-3.24-4.19-11.26-5.57-13.76h4.8c22.17,0.92,25.57,12.49,25.881,13.83C281.852,332.936,276.372,344.815,256.302,345.745z\
					 M320.182,388.745h17.82c7.17,0,13,5.83,13,13s-5.83,13-13,13h-17.82V388.745z M292.182,332.976c0.57-0.181,1.01-0.65,1.17-1.23\
					h51.14c0.891,2.09,1.551,4.07,1.551,5.31c0,1.511-0.95,4.12-2.091,6.69h-24.77v14h-12.27c-0.33-0.49-0.9-0.81-1.54-0.81\
					c-0.641,0-1.21,0.319-1.54,0.81h-11.65V332.976z M292.182,358.745h11.32c-0.011,0.02-0.011,0.05-0.011,0.07\
					c0,0.97,0.74,1.77,1.69,1.859v35.07h14v12h-27V358.745z M210.182,326.625c0.81-0.2,1.41-0.93,1.41-1.81\
					c0-0.021,0-0.051-0.01-0.07h38.29c1.3,2.78,2.489,5.75,2.489,7.4c0,1.3-0.699,3.399-1.62,5.6h-22.119c-0.301-0.6-0.931-1-1.65-1\
					s-1.35,0.4-1.65,1h-15.14V326.625z M210.182,338.745h14.92c0.04,0.71,0.47,1.31,1.08,1.58v17.42h-16V338.745z M319.182,449.745\
					h-109v-91h16v79h93V449.745z M338.002,454.745h-17.82v-26h17.82c7.17,0,13,5.83,13,13S345.172,454.745,338.002,454.745z\
					 M385.182,426.745v15h-33.18c0-7.72-6.28-14-14-14h-18.82v9h-92v-78h64v50h28v7h18.82c7.38,0,13.449-5.74,13.96-13h33.22v11h9.83\
					c0.76,1.9,1.31,3.65,1.29,4.74c-0.04,1.81-1.38,5.21-2.771,8.26H385.182z M396.302,432.745h-4.58c0.52-0.99,1.479-2.87,2.46-5\
					c1.52-3.28,3.08-7.14,3.12-9.24c0.07-3.25-4.19-11.26-5.561-13.76h4.771c22.12,1.83,25.57,12.54,25.9,13.84\
					C421.842,419.965,416.352,431.815,396.302,432.745z'), 
		d = r.path('M648.212,267.745c-0.931-2.83-5.601-12.26-26.65-14h-6.53l0.42,0.75c0.04,0.06,2.421,4.28,4.131,8.25\
					h-8.4v-11h-34.18c0-7.72-6.28-14-14-14h-18.82v7h-13v-34.24c0.63-0.29,1.07-0.94,1.07-1.69c0-0.02,0-0.05-0.011-0.07h12.94v-14\
					h23.31c-1.56,3.38-3.27,6.43-3.3,6.48l0.87,0.49c0.24-0.43,5.99-10.68,5.98-14.67c0-1.48-0.83-3.85-1.86-6.24\
					c-0.01-0.02-0.02-0.04-0.03-0.06c-1.689-3.9-3.939-7.85-4.09-8.12l-0.87,0.5c0.04,0.06,2.19,3.84,3.87,7.62h-50.689\
					c-0.2-0.81-0.931-1.41-1.811-1.41s-1.61,0.6-1.81,1.41h-6.521c-0.89-2.96-5.49-13.12-26.68-14h-6.53l0.43,0.75\
					c0.061,0.1,5.921,10.47,5.851,13.99c-0.08,3.78-5.8,14.42-5.86,14.52l-0.399,0.74h6.29c21.859-1,27.029-14.82,27.069-14.96\
					l0.021-0.04h6.35c0.18,0.66,0.73,1.17,1.41,1.31v24.69h-64v-17.26c0.9-0.09,1.61-0.83,1.66-1.74h21.46\
					c-1.67,3.79-3.76,7.52-3.8,7.58l0.88,0.49c0.24-0.43,5.99-10.69,5.979-14.67c-0.02-3.93-5.739-14-5.989-14.42l-0.86,0.49\
					c0.03,0.05,1.46,2.56,2.89,5.53h-38.149c-0.33-0.49-0.9-0.81-1.54-0.81c-0.641,0-1.21,0.32-1.54,0.81H63.182v1h369.66\
					c-0.01,0.02-0.01,0.05-0.01,0.07c0,0.85,0.569,1.57,1.35,1.79v11.14h-371v1h371v19h-20v1h20v92h110v5h18.82\
					c7.38,0,13.449-5.74,13.96-13h34.22v-15h6.89c-1.34,2.87-2.59,5.21-2.62,5.26l-0.399,0.74h6.28\
					c21.859-1,27.029-14.82,27.08-14.96l0.01-0.04h14.76v-1H648.212z M481.302,195.745h-4.59c1.33-2.53,5.52-10.78,5.59-14.24\
					c0.07-3.24-4.19-10.76-5.57-13.76h4.8c22.17,1,25.57,12.49,25.881,13.83C506.852,182.935,501.372,194.815,481.302,195.745z\
					 M545.182,238.745h17.82c7.17,0,13,5.83,13,13s-5.83,13-13,13h-17.82V238.745z M517.182,182.975c0.57-0.18,1.01-0.65,1.17-1.23\
					h51.14c0.891,2.09,1.551,4.07,1.551,5.31c0,1.51-0.95,4.12-2.091,6.69h-24.77v14h-12.27c-0.33-0.49-0.9-0.81-1.54-0.81\
					c-0.641,0-1.21,0.32-1.54,0.81h-11.65V182.975z M517.182,208.745h11.32c-0.011,0.02-0.011,0.05-0.011,0.07\
					c0,0.97,0.74,1.77,1.69,1.86v35.07h14v12h-27V208.745z M435.182,176.625c0.81-0.2,1.41-0.93,1.41-1.81c0-0.02,0-0.05-0.01-0.07\
					h38.29c1.3,2.78,2.489,5.75,2.489,7.4c0,1.3-0.699,3.4-1.62,5.6h-22.119c-0.301-0.6-0.931-1-1.65-1s-1.35,0.4-1.65,1h-15.14\
					V176.625z M435.182,188.745h14.92c0.04,0.71,0.47,1.31,1.08,1.58v17.42h-16V188.745z M544.182,299.745h-109v-91h16v79h93V299.745\
					z M563.002,304.745h-17.82v-26h17.82c7.17,0,13,5.83,13,13S570.172,304.745,563.002,304.745z M610.182,276.745v15h-33.18\
					c0-7.72-6.28-14-14-14h-18.82v9h-92v-78h64v50h28v7h18.82c7.38,0,13.449-5.74,13.96-13h33.22v11h9.83\
					c0.76,1.9,1.31,3.65,1.29,4.74c-0.04,1.81-1.38,5.21-2.771,8.26H610.182z M621.302,282.745h-4.58c0.52-0.99,1.479-2.87,2.46-5\
					c1.52-3.28,3.08-7.14,3.12-9.24c0.07-3.25-4.19-10.76-5.561-13.76h4.771c22.12,2,25.57,12.54,25.9,13.84\
					C646.842,269.965,641.352,281.815,621.302,282.745z'), 
		e = r.path('M826.912,35.745c-0.881-2.96-5.48-13.12-26.671-14h-6.529l0.42,0.75c0.06,0.1,5.93,10.47,5.859,13.99\
				c-0.079,3.78-5.8,14.42-5.859,14.52l-0.4,0.74h6.311c21.83-2.01,26.84-14.42,27.05-14.94l0.02-0.06h97.07v-1H826.912z\
				 M799.972,50.745h-4.57c1.33-2.53,5.511-10.78,5.59-14.24c0.061-3.24-4.189-10.76-5.569-13.76h4.8\
				c22.13,1,25.55,12.45,25.88,13.83C825.512,37.895,819.991,48.895,799.972,50.745z'), 
		f = r.path('M873.212,117.745c-0.931-2.83-5.601-12.26-26.65-14h-6.53l0.42,0.75c0.04,0.06,2.421,4.28,4.131,8.25\
				h-8.4v-11h-34.18c0-7.72-6.28-14-14-14h-18.82v7h-13v-34.24c0.63-0.29,1.07-0.94,1.07-1.69c0-0.02,0-0.05-0.011-0.07h12.94v-14\
				h23.31c-1.56,3.38-3.27,6.43-3.3,6.48l0.87,0.49c0.24-0.43,5.99-10.68,5.98-14.67c0-1.48-0.83-3.85-1.86-6.24\
				c-0.01-0.02-0.02-0.04-0.03-0.06c-1.689-3.9-3.939-7.85-4.09-8.12l-0.87,0.5c0.04,0.06,2.19,3.84,3.87,7.62h-50.689\
				c-0.2-0.81-0.931-1.41-1.811-1.41s-1.61,0.6-1.81,1.41h-6.521c-0.89-2.96-5.49-13.12-26.68-14h-6.53l0.43,0.75\
				c0.061,0.1,5.921,10.47,5.851,13.99c-0.08,3.78-5.8,14.42-5.86,14.52l-0.399,0.74h6.29c21.859-1,27.029-14.82,27.069-14.96\
				l0.021-0.04h6.35c0.18,0.66,0.73,1.17,1.41,1.31v24.69h-64v0.5h-1v-0.5h-16v-19h14.92c0.04,0.71,0.47,1.31,1.08,1.58v17.42h1\
				v-17.26c0.9-0.09,1.61-0.83,1.66-1.74h21.46c-1.67,3.79-3.76,7.52-3.8,7.58l0.88,0.49c0.24-0.43,5.99-10.69,5.979-14.67\
				c-0.02-3.93-5.739-14-5.989-14.42l-0.86,0.49c0.03,0.05,1.46,2.56,2.89,5.53h-38.149c-0.33-0.49-0.9-0.81-1.54-0.81\
				c-0.641,0-1.21,0.32-1.54,0.81H60.182v1h597.66c-0.01,0.02-0.01,0.05-0.01,0.07c0,0.85,0.569,1.57,1.35,1.79v11.14h-599v1h599v19\
				h-20v1h20v92h110v5h18.82c7.38,0,13.449-5.74,13.96-13h34.22v-15h6.89c-1.34,2.87-2.59,5.21-2.62,5.26l-0.399,0.74h6.28\
				c21.859-1,27.029-14.82,27.08-14.96l0.01-0.04h49.26v-1H873.212z M706.302,45.745h-4.59c1.33-2.53,5.52-10.78,5.59-14.24\
				c0.07-3.24-4.19-10.76-5.57-13.76h4.8c22.17,1,25.57,12.49,25.881,13.83C731.852,32.935,726.372,44.815,706.302,45.745z\
				 M660.182,26.625c0.81-0.2,1.41-0.93,1.41-1.81c0-0.02,0-0.05-0.01-0.07h38.29c1.3,2.78,2.489,5.75,2.489,7.4\
				c0,1.3-0.699,3.4-1.62,5.6h-22.119c-0.301-0.6-0.931-1-1.65-1s-1.35,0.4-1.65,1h-15.14V26.625z M770.182,88.745h17.82\
				c7.17,0,13,5.83,13,13s-5.83,13-13,13h-17.82V88.745z M742.182,32.975c0.57-0.18,1.01-0.65,1.17-1.23h51.14\
				c0.891,2.09,1.551,4.07,1.551,5.31c0,1.51-0.95,4.12-2.091,6.69h-24.77v14h-12.27c-0.33-0.49-0.9-0.81-1.54-0.81\
				c-0.641,0-1.21,0.32-1.54,0.81h-11.65V32.975z M742.182,58.745h11.32c-0.011,0.02-0.011,0.05-0.011,0.07\
				c0,0.97,0.74,1.77,1.69,1.86v35.07h14v12h-27V58.745z M769.182,149.745h-109v-91h16v79h93V149.745z M788.002,154.745h-17.82v-26\
				h17.82c7.17,0,13,5.83,13,13S795.172,154.745,788.002,154.745z M835.182,126.745v15h-33.18c0-7.72-6.28-14-14-14h-18.82v9h-92\
				v-78h64v50h28v7h18.82c7.38,0,13.449-5.74,13.96-13h33.22v11h9.83c0.76,1.9,1.31,3.65,1.29,4.74c-0.04,1.81-1.38,5.21-2.771,8.26\
				H835.182z M846.302,132.745h-4.58c0.52-0.99,1.479-2.87,2.46-5c1.52-3.28,3.08-7.14,3.12-9.24c0.07-3.25-4.19-10.76-5.561-13.76\
				h4.771c22.12,2,25.57,12.54,25.9,13.84C871.842,119.965,866.352,131.815,846.302,132.745z'), 
		g = r.path('M516.182,335.745v-21h-194v-104h37.09l-3.35,3.11l0.68,0.73l4.4-4.08l-0.82-0.76l-3.58-3.33l-0.68,0.73\
				l2.79,2.6h-37.53v106h194v20h-138.27c-0.881-2.96-5.48-13.12-26.671-14h-6.529l0.42,0.75c0.06,0.1,5.93,10.47,5.859,13.99\
				c-0.079,3.779-5.8,14.42-5.859,14.52l-0.4,0.74h6.311c21.83-2.01,26.84-14.42,27.05-14.94l0.02-0.06h138.07v81h-22v1h23v-82h407\
				v-1H516.182z M349.972,350.745h-4.57c1.33-2.53,5.511-10.78,5.59-14.24c0.061-3.24-4.189-11.26-5.569-13.76h4.8\
				c22.13,0.92,25.55,12.45,25.88,13.83C375.512,337.896,369.991,348.896,349.972,350.745z'), 
		h = r.path('M742.182,185.745v-21h-195v-105h38.09l-3.35,3.11l0.68,0.73l4.4-4.08l-0.82-0.76l-3.58-3.33l-0.68,0.73\
					l2.79,2.6h-38.53v107h195v20h-139.27c-0.881-2.96-5.48-13.12-26.671-14h-6.529l0.42,0.75c0.06,0.1,5.93,10.47,5.859,13.99\
					c-0.079,3.78-5.8,14.42-5.859,14.52l-0.4,0.74h6.311c21.83-2.01,26.84-14.42,27.05-14.94l0.02-0.06h139.07v82h-23v1h24v-83h180\
					v-1H742.182z M574.972,200.745h-4.57c1.33-2.53,5.511-10.78,5.59-14.24c0.061-3.24-4.189-10.76-5.569-13.76h4.8\
					c22.13,1,25.55,12.45,25.88,13.83C600.512,187.895,594.991,198.895,574.972,200.745z')).attr({
      fill: black
    });
    text_size = '20px';
    subscript_size = '12px';
    a0 = r.set().push(inputA_0 = r.text(45, 470, "A").attr({
      'font-size': text_size
    }), subA_0 = r.text(58, 475, "0").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'font-family': fontfamily
    });
    b0 = r.set().push(inputB_0 = r.text(45, 490, "B").attr({
      'font-size': text_size
    }), subB_0 = r.text(58, 495, "0").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'font-family': fontfamily
    });
    ci0 = r.set().push(CI_0 = r.text(58, 520, "carry\nin").attr({
      'font-size': text_size
    }), subCI_0 = r.text(65, 540, "0").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'text-anchor': 'end',
      'font-family': fontfamily
    });
    co0 = r.set().push(CO_0 = r.text(337, 567, "carry\nout").attr({
      'font-size': text_size
    }), subCO_0 = r.text(355, 585, "0").attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'middle',
      'font-family': fontfamily
    });
    sum0 = r.set().push(sum_0 = r.text(927, 485, 'sum').attr({
      'font-size': text_size
    }), sub_s0 = r.text(965, 490, '0').attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'start',
      'font-family': fontfamily
    });
    a1 = r.set().push(inputA_1 = r.text(45, 320, "A").attr({
      'font-size': text_size
    }), subA_1 = r.text(58, 325, "1").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'font-family': fontfamily
    });
    b1 = r.set().push(inputB_1 = r.text(45, 340, "B").attr({
      'font-size': text_size
    }), subB_1 = r.text(58, 345, "1").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'font-family': fontfamily
    });
    ci1 = r.set().push(CI_1 = r.text(163, 363, "carry\nin").attr({
      'font-size': text_size
    }), subCI_1 = r.text(175, 380, "1").attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'middle',
      'font-family': fontfamily
    });
    co1 = r.set().push(CO_1 = r.text(463, 417, "carry\nout").attr({
      'font-size': text_size
    }), subCO_1 = r.text(480, 435, "1").attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'middle',
      'font-family': fontfamily
    });
    sum1 = r.set().push(sum_1 = r.text(927, 335, 'sum').attr({
      'font-size': text_size
    }), sub_s1 = r.text(965, 340, '1').attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'start',
      'font-family': fontfamily
    });
    a2 = r.set().push(inputA_2 = r.text(45, 173, "A").attr({
      'font-size': text_size
    }), subA_2 = r.text(58, 177, "2").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'font-family': fontfamily
    });
    b2 = r.set().push(inputB_2 = r.text(45, 193, "B").attr({
      'font-size': text_size
    }), subB_2 = r.text(58, 197, "2").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'font-family': fontfamily
    });
    ci2 = r.set().push(CI_2 = r.text(387, 211, "carry\nin").attr({
      'font-size': text_size
    }), subCI_2 = r.text(400, 230, "2").attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'middle',
      'font-family': fontfamily
    });
    co2 = r.set().push(CO_2 = r.text(689, 267, "carry\nout").attr({
      'font-size': text_size
    }), subCO_2 = r.text(708, 285, "2").attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'middle',
      'font-family': fontfamily
    });
    sum2 = r.set().push(sum_2 = r.text(927, 185, 'sum').attr({
      'font-size': text_size
    }), sub_s2 = r.text(965, 190, '2').attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'start',
      'font-family': fontfamily
    });
    a3 = r.set().push(inputA_3 = r.text(45, 20, "A").attr({
      'font-size': text_size
    }), subA_3 = r.text(56, 25, "3").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'font-family': fontfamily
    });
    b3 = r.set().push(inputB_3 = r.text(45, 40, "B").attr({
      'font-size': text_size
    }), subB_3 = r.text(56, 45, "3").attr({
      'font-size': subscript_size
    })).attr({
      fill: blue,
      'font-family': fontfamily
    });
    ci3 = r.set().push(CI_3 = r.text(615, 62, "carry\nin").attr({
      'font-size': text_size
    }), subCI_3 = r.text(628, 80, "3").attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'middle',
      'font-family': fontfamily
    });
    co3 = r.set().push(CO_3 = r.text(927, 117, "carry\nout").attr({
      'font-size': text_size
    }), subCO_3 = r.text(960, 133, "3").attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'start',
      'font-family': fontfamily
    });
    sum3 = r.set().push(sum_3 = r.text(927, 35, 'sum').attr({
      'font-size': text_size
    }), sub_s3 = r.text(965, 40, '3').attr({
      'font-size': subscript_size
    })).attr({
      fill: black,
      'text-anchor': 'start',
      'font-family': fontfamily
    });

    reset = r.set().push(
    	labelsbutton = r.text(920, 610, 'Show Labels')
    		.attr({
    		  'font-size': text_size,
    		  fill: blue
    		})
    ).click(function(){
    	subCI_0.show();
      	subCO_0.show();
      	subCI_1.show();
      	subCO_1.show();
      	subCI_2.show();
      	subCO_2.show();
      	subCI_3.show();
      	subCO_3.show();
	    sub_s0.show();
	    sub_s1.show();
	    sub_s2.show();
	    sub_s3.show();
	    subA_0.show();
		subA_1.show();
		subA_2.show();
		subA_3.show();
		subB_0.show();
		subB_1.show();
		subB_2.show();
		subB_3.show();
		subCI_0.show(); 
		inputA_0.attr("text","A");
		inputB_0.attr("text","B");
		CI_0.attr("text","carry\nin");
		CO_0.attr("text","carry\nout");
		sum_0.attr("text","sum");
		inputA_1.attr("text","A");
		inputB_1.attr("text","B");
		CI_1.attr("text","carry\nin");
		CO_1.attr("text","carry\nout");
		sum_1.attr("text","sum");
		inputA_2.attr("text","A");
		inputB_2.attr("text","B");
		CI_2.attr("text","carry\nin");
		CO_2.attr("text","carry\nout");
		sum_2.attr("text","sum");
		inputA_3.attr("text","A");
		inputB_3.attr("text","B");
		CI_3.attr("text","carry\nin");
		CO_3.attr("text","carry\nout");
		sum_3.attr("text","sum");
		

      	 
    });

    labels = r.set().push(a0, b0, ci0, co0, sum0, a1, b1, ci1, co1, sum1, a2, b2, ci2, co2, sum2, a3, b3, ci3, co3, sum3);
    rca.push(labels);
    a0_clicked = {
      flag: false
    };
    a1_clicked = {
      flag: false
    };
    a2_clicked = {
      flag: false
    };
    a3_clicked = {
      flag: false
    };
    b0_clicked = {
      flag: false
    };
    b1_clicked = {
      flag: false
    };
    b2_clicked = {
      flag: false
    };
    b3_clicked = {
      flag: false
    };
    carryIn_clicked = {
      flag: false
    };

    clickInputs = function(set, text, subscript, flag) {
     return set.click(function() {
        text.attr('text', toggle(text.attr('text')));
        subscript.hide();
        flag.flag = true;
        updateOutput();
        return showWires();
      });
    };
    clickInputs(a0, inputA_0, subA_0, a0_clicked);
    clickInputs(a1, inputA_1, subA_1, a1_clicked);
    clickInputs(a2, inputA_2, subA_2, a2_clicked);
    clickInputs(a3, inputA_3, subA_3, a3_clicked);
    clickInputs(b0, inputB_0, subB_0, b0_clicked);
    clickInputs(b1, inputB_1, subB_1, b1_clicked);
    clickInputs(b2, inputB_2, subB_2, b2_clicked);
    clickInputs(b3, inputB_3, subB_3, b3_clicked);
    clickInputs(ci0, CI_0, subCI_0, carryIn_clicked);
    toggle = function(bit) {
      if (bit === 0 || bit === '0') {
        return 1;
      } else {
        return 0;
      }
    };

    getValue = function(input) {
      var inputtext;
      inputtext = input.attr('text');
      if (typeof inputtext === 'string') {
        return 0;
      } else {
        return inputtext;
      }
    };
    changeCarry = function(elementout, elementin, logic) {
      elementout.attr({
        'text': logic,
        fill: orange
      });
      return elementin.attr({
        'text': logic,
        fill: orange
      });
    };
    changeSum = function(element, sum) {
      return element.attr({
        text: sum
      });
    };
    updateOutput = function() {
      var a_0, a_1, a_2, a_3, b_0, b_1, b_2, b_3, ci_0, cin_1, cin_2, cin_3, cout3, s_0, s_1, s_2, s_3;
      subCI_0.hide();
      subCO_0.hide();
      subCI_1.hide();
      subCO_1.hide();
      subCI_2.hide();
      subCO_2.hide();
      subCI_3.hide();
      subCO_3.hide();
      a_0 = getValue(inputA_0);
      a_1 = getValue(inputA_1);
      a_2 = getValue(inputA_2);
      a_3 = getValue(inputA_3);
      b_0 = getValue(inputB_0);
      b_1 = getValue(inputB_1);
      b_2 = getValue(inputB_2);
      b_3 = getValue(inputB_3);
      ci_0 = getValue(CI_0);
      cin_1 = ci_0 & (a_0 ^ b_0) | (a_0 & b_0);
      cin_2 = cin_1 & (a_1 ^ b_1) | (a_1 & b_1);
      cin_3 = cin_2 & (a_2 ^ b_2) | (a_2 & b_2);
      cout3 = cin_3 & (a_3 ^ b_3) | (a_3 & b_3);
      changeCarry(CO_0, CI_1, cin_1);
      changeCarry(CO_1, CI_2, cin_2);
      changeCarry(CO_2, CI_3, cin_3);
      changeCarry(CO_3, CO_3, cout3);
      sub_s0.hide();
      sub_s1.hide();
      sub_s2.hide();
      sub_s3.hide();
      s_0 = (a_0 ^ b_0) ^ ci_0;
      s_1 = (a_1 ^ b_1) ^ cin_1;
      s_2 = (a_2 ^ b_2) ^ cin_2;
      s_3 = (a_3 ^ b_3) ^ cin_3;
      changeSum(sum_0, s_0);
      changeSum(sum_1, s_1);
      changeSum(sum_2, s_2);
      return changeSum(sum_3, s_3);
    };
    makeMovingLine = function(path, dashType, color, width, htmlid) {
      var i, interval, move, name;
      name = r.path(path).attr({
        'stroke-dasharray': dashType,
        'stroke-width': width,
        stroke: color
      });
      name.node.id = htmlid;
      $('#' + htmlid).hide();
      i = 0;
      move = function() {
        $('#' + htmlid).attr('stroke-dashoffset', i--);
        if (i < -20) {
          return i = 0;
        }
      };
      return interval = window.setInterval(move, 50);
    };
    showWires = function() {
      var a_0, a_1, a_2, a_3, b_0, b_1, b_2, b_3, ci_0, co_0, co_1, co_2, co_3;
      a_0 = getValue(inputA_0);
      a_1 = getValue(inputA_1);
      a_2 = getValue(inputA_2);
      a_3 = getValue(inputA_3);
      b_0 = getValue(inputB_0);
      b_1 = getValue(inputB_1);
      b_2 = getValue(inputB_2);
      b_3 = getValue(inputB_3);
      ci_0 = getValue(CI_0);
      showWiresHelper(ci_0, ['I']);
      showWiresHelper(a_0, ['G']);
      showWiresHelper(b_0, ['H']);
      showWiresHelper(a_0 ^ b_0, ['L']);
      showWiresHelper((a_0 ^ b_0) & ci_0, ['Q']);
      showWiresHelper(a_0 & b_0, ['R']);
      co_0 = (a_0 & b_0) | ((a_0 ^ b_0) & ci_0);
      showWiresHelper(co_0, ['S']);
      showWiresHelper((a_0 ^ b_0) ^ ci_0, ['O']);
      showWiresHelper(a_1, ['E']);
      showWiresHelper(b_1, ['F']);
      showWiresHelper(a_1 ^ b_1, ['V']);
      showWiresHelper((a_1 ^ b_1) & co_0, ['Z']);
      showWiresHelper(a_0 & b_0, ['AA']);
      co_1 = (a_1 & b_1) | ((a_1 ^ b_1) & co_0);
      showWiresHelper(co_1, ['AB']);
      showWiresHelper((a_1 ^ b_1) ^ co_0, ['X']);
      showWiresHelper(a_2, ['C']);
      showWiresHelper(b_2, ['D']);
      showWiresHelper(a_2 ^ b_2, ['AE']);
      showWiresHelper((a_2 ^ b_2) & co_1, ['AI']);
      showWiresHelper(a_2 & b_2, ['AJ']);
      co_2 = (a_2 & b_2) | ((a_2 ^ b_2) & co_1);
      showWiresHelper(co_2, ['AK']);
      showWiresHelper((a_2 ^ b_2) ^ co_1, ['AH']);
      showWiresHelper(a_3, ['A']);
      showWiresHelper(b_3, ['B']);
      showWiresHelper(a_3 ^ b_3, ['AN']);
      showWiresHelper((a_3 ^ b_3) & co_2, ['AQ']);
      showWiresHelper(a_3 & b_3, ['AR']);
      co_3 = (a_3 & b_3) | ((a_3 ^ b_3) & co_2);
      showWiresHelper(co_3, ['AT']);
      return showWiresHelper((a_3 ^ b_3) ^ co_2, ['AS']);
    };
    showWiresHelper = function(input, correspondingWiresArray) {
      var letter, _i, _j, _len, _len1, _results, _results1;
      if (input) {
        _results = [];
        for (_i = 0, _len = correspondingWiresArray.length; _i < _len; _i++) {
          letter = correspondingWiresArray[_i];
          _results.push($('#line' + letter).show());
        }
        return _results;
      } else {
        _results1 = [];
        for (_j = 0, _len1 = correspondingWiresArray.length; _j < _len1; _j++) {
          letter = correspondingWiresArray[_j];
          _results1.push($('#line' + letter).hide());
        }
        return _results1;
      }
    };
    makeMovingLine("M60, 24 h 639 M660, 24 v126 h109", ".", white, 3, "lineA");
    makeMovingLine("M60, 38 h 639 M677, 38 v99 h90", ".", white, 3, "lineB");
    makeMovingLine("M60, 174 h 413 M435, 173 v127 h110", ".", white, 3, "lineC");
    makeMovingLine("M60, 188 h 413 M452, 190 v 97 h 93", ".", white, 3, "lineD");
    makeMovingLine("M60, 324 h 187 M209.5, 323 v 127 h 110", ".", white, 3, "lineE");
    makeMovingLine("M60, 338 h 187 M227, 340 v 97 h 93", ".", white, 3, "lineF");
    makeMovingLine("M60, 474 h 61 M83, 475 v 125 h 109", ".", white, 3, "lineG");
    makeMovingLine("M60, 488 h 61 M100, 490 v 97 h 90", ".", white, 3, "lineH");
    makeMovingLine("M60, 508 h 133 v-14 h 23 M179, 506 v 39 h 12", ".", white, 3, "lineI");
    makeMovingLine("M157, 481 h 60 M165, 481 v 77 h 25", ".", white, 3, "lineL");
    makeMovingLine("M250, 486.5 h 673 v1", ".", white, 3, "lineO");
    makeMovingLine("M223, 552 h 35 v 11 h10", ".", white, 3, "lineQ");
    makeMovingLine("M223, 592 h 35 v -14 h10", ".", white, 3, "lineR");
    makeMovingLine("M297, 568 h 15 m 53,1 h20 v-108 h-289 v-102 h39 m 53,-1 h132 v -14 h22 M306, 357 v38 h13", ".", white, 3, "lineS");
    makeMovingLine("M291.5, 330 v 78 h 27M283, 331 h62 ", ".", white, 3, "lineV");
    makeMovingLine("M377, 336 h545 v1", ".", white, 3, "lineX");
    makeMovingLine("M353, 402 h33 v12 h 9 ", ".", white, 3, "lineZ");
    makeMovingLine("M353, 442 h33 v-14 h 9 ", ".", white, 3, "lineAA");
    makeMovingLine("M423, 418 h15 m 55,0 h22.5 v-103 h -194  v-105 h35 m57,-2 h132 v -14 h22 M531, 207 v38 h13", ".", white, 3, "lineAB");
    makeMovingLine("M516.5, 180 v 78 h 27 M508, 181 h62", ".", white, 3, "lineAE");
    makeMovingLine("M603, 186 h320 v1", ".", white, 3, "lineAH");
    makeMovingLine("M577, 252 h34 v11 h10 ", ".", white, 3, "lineAI");
    makeMovingLine("M577, 292 h34 v-14 h8 ", ".", white, 3, "lineAJ");
    makeMovingLine("M650, 268 h13 m54, 1 h25 v-104 h-195.5 v-106 h37 m55,-1 h131 v-14 h 24 M756, 60 v35 h 13", ".", white, 3, "lineAK");
    makeMovingLine("M735, 31 h59 M741.5, 31 v77 h 27", ".", white, 3, "lineAN");
    makeMovingLine("M801, 102 h35 v 11 h10", ".", white, 3, "lineAQ");
    makeMovingLine("M801, 142 h35 v-15 h7", ".", white, 3, "lineAR");
    makeMovingLine("M827, 36 h100 v1", ".", white, 3, "lineAS");
    return makeMovingLine("M873, 118 h50 v1", ".", white, 3, "lineAT");
  };

}).call(this);
