// Generated by CoffeeScript 1.3.1
(function() {
  var black, interaction_color, gray, green, orange, purple, red, white, yellow;

  black = '#000';

  white = "#a5a5a5";

  gray = "#00f";

  orange = "#a5a5a5";

  yellow = "#a5a5a5";

  green = "#a5a5a5";

  purple = "#ff9800"; 

  interaction_color = '#ff9800';  // interaction_color

  red = "#33CCFF";  

  window.onload = function() {
    var makeMovingLine, n_ground, n_input, n_inputText, n_label, n_outText, n_outWire, n_power, n_transistor, p_bubble, p_ground, p_input, p_inputText, p_label, p_outText, p_outWire, p_power, p_transistor, r, showWires, toggle;
    r = new Raphael('transistor-ralph', 700, 400);
    n_power = r.path('M75,50 h 200').attr({
      stroke: red,
      'stroke-width': '5px'
    });
    n_transistor = r.path("M175, 50 v100 h-50 v50 h50 v100").attr({
      stroke: black,
      'stroke-width': '5px'
    });
    n_ground = r.path("M75, 300 h200").attr({
      stroke: black,
      'stroke-width': '5px'
    });
    n_input = r.path("M115, 150 v50 m0,-25 h-20").attr({
      stroke: black,
      'stroke-width': '3px'
    });
    n_inputText = r.text(80, 175, 0).attr({
      fill: interaction_color,
      'font-size': '30px',
      'cursor': 'pointer'
    });
    n_outWire = r.path("M175,120 h50").attr({
      stroke: black,
      'stroke-width': '5px'
    });
    n_outText = r.text(245, 120, "1").attr({
      fill: black,
      'font-size': '30px'
    });
    n_label = r.text(175, 350, "n-type transistor").attr({
      fill: black,
      'font-size': '30px'
    }).hide();
    p_transistor = r.path("M525, 50 v100 h-50 v50 h50 v100").attr({
      stroke: black,
      'stroke-width': '5px'
    });
    p_input = r.path("M465, 150 v50 m0,-25 h-20").attr({
      stroke: black,
      'stroke-width': '3px'
    });
    p_bubble = r.circle(458, 175, 5).attr({
      fill: '#fff',
      stroke: black,
      'stroke-width': '2px'
    });
    p_power = r.path('M425,50 h 200').attr({
      stroke: red,
      'stroke-width': '5px'
    });
    p_ground = r.path("M425, 300 h200").attr({
      stroke: black,
      'stroke-width': '5px'
    });
    p_inputText = r.text(430, 175, 0).attr({
      fill: interaction_color,
      'font-size': '30px',
      'cursor': 'pointer'
    });
    p_outWire = r.path("M525,120 h50").attr({
      stroke: black,
      'stroke-width': '5px'
    });
    p_outText = r.text(595, 120, "0").attr({
      fill: black,
      'font-size': '30px'
    });
    p_label = r.text(525, 350, "p-type transistor").attr({
      fill: black,
      'font-size': '30px'
    }).hide();
    toggle = function(bit) {
      if (typeof bit === 'string') {
        return 1;
      }
      if (bit) {
        return 0;
      } else {
        return 1;
      }
    };
    n_inputText.click(function() {
      this.attr('text', toggle(this.attr('text')));
      n_outText.attr('text', toggle(n_inputText.attr('text')));
      return showWires();
    });
    p_inputText.click(function() {
      this.attr('text', toggle(this.attr('text')));
      p_outText.attr('text', p_inputText.attr('text'));
      return showWires();
    });
    makeMovingLine = function(path, dashType, color, width, htmlid) {
      var i, interval, move, name;
      name = r.path(path).attr({
        'stroke-dasharray': dashType,
        'stroke-width': width,
        stroke: color
      });
      name.node.id = htmlid;
      i = 0;
      move = function() {
        $('#' + htmlid).attr('stroke-dashoffset', i--);
        if (i < -20) {
          return i = 0;
        }
      };
      return interval = window.setInterval(move, 50);
    };
    makeMovingLine("M75, 50 h 200 v0", ".", white, 3, "N_POWER");
    makeMovingLine("M175, 50 v 70 h0", ".", red, 3, "N_top");
    makeMovingLine("M175, 120 h50 v0", ".", red, 3, "N_output");
    makeMovingLine("M175, 120 v 180 h0", ".", red, 3, "N_inputON");
    makeMovingLine("M425, 50 h 200 v0", ".", white, 3, "P_POWER");
    makeMovingLine("M525, 50 v 70 h0", ".", red, 3, "P_top");
    makeMovingLine("M525, 120 h50 v0", ".", red, 3, "P_output");
    makeMovingLine("M525, 120 v 180 h0", ".", red, 3, "P_inputON");
    $('#N_inputON').hide();
    $('#P_output').hide();
    return showWires = function() {
      n_input = parseInt(n_inputText.attr('text'));
      p_input = parseInt(p_inputText.attr('text'));
      if (n_input) {
        $('#N_inputON').show();
        $('#N_output').hide();
      } else {
        $('#N_inputON').hide();
        $('#N_output').show();
      }
      if (p_input) {
        $('#P_inputON').hide();
        return $('#P_output').show();
      } else {
        $('#P_inputON').show();
        return $('#P_output').hide();
      }
    };
  };

}).call(this);
